# Configuration for RL Bot Training

# Training parameters
training:
  total_timesteps: 10000000
  batch_size: 4096  # ALIGNÉ : 8 envs × 512 steps = 4096 (throughput propre)
  n_steps: 512  # Steps par env avant update (8 × 512 = 4096 = batch_size)
  n_epochs: 4  # Réduit de 10 pour aller plus vite
  learning_rate: 0.0003  # Augmenté pour apprendre plus vite
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  save_interval: 100000  # Sauvegarde plus fréquente
  log_interval: 1000  # Log plus fréquent pour voir les progrès
  seed: 42  # Seed pour la reproductibilité
  eval_freq: 50000  # Fréquence d'évaluation du modèle
  n_eval_episodes: 10  # Nombre d'épisodes d'évaluation

# Environment parameters
environment:
  num_envs: 8  # Nombre d'environnements parallèles (ajusté selon CPU)
  tick_skip: 8  # Frame skip (8 = 120Hz / 15fps, RÉDUIT de 160 pour meilleur apprentissage)
  spawn_opponents: true
  team_size: 1
  timeout_seconds: 300
  truncate_on_goal: false
  deterministic_eval: true  # Évaluation déterministe
  auto_adjust_envs: true  # Ajuste num_envs selon cpu_count()

# Network architecture (OPTIMISÉ - plus petit = plus rapide)
network:
  policy_layers: [256, 256, 256]  # Réduit de 512 -> entraînement 4x plus rapide
  value_layers: [256, 256, 256]
  activation: "relu"
  use_lstm: false
  lstm_hidden_size: 256

# Reward weights (OPTIMISÉ POUR MARQUER DES BUTS)
rewards:
  goal_weight: 100.0  # Augmenté ! Marquer un but = super important
  concede_weight: -100.0  # Augmenté ! Encaisser = très mauvais
  touch_ball_weight: 1.0  # Augmenté légèrement
  velocity_player_to_ball_weight: 0.5  # Augmenté - aller vers la balle
  velocity_ball_to_goal_weight: 2.0  # TRÈS AUGMENTÉ - pousser vers le but !
  save_boost_weight: 0.05  # Réduit - moins important que marquer
  demo_weight: 1.0  # Réduit - pas prioritaire au début
  got_demoed_weight: -1.0  # Réduit
  align_ball_goal_weight: 1.0  # Augmenté - bon positionnement
  aerial_weight: 0.5  # Ok
  flip_reset_weight: 0.0  # Désactivé - trop avancé pour le début
  wall_touch_weight: 0.0  # Désactivé - pas prioritaire

# Logging
logging:
  tensorboard: true
  wandb: false
  wandb_project: "rocket-league-bot"
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
